const discografia = [
  {
    "id": "1",
    "img": "img/1991.jpg",
    "name": "Aniversário do Tatu",
    "description": "1991 • Álbum",
    "link": "https://www.letras.mus.br/sandy-e-junior-musicas/discografia/aniversario-do-tatu-1991/",
    "list": [
        "Aniversário do Tatu",
        "Casamento Natural",
        "Bicho Preguiça",
        "Eu Não Tenho Tamanho",
        "A Horta",
        "Charada",
        "O Presentinho",
        "O Vira-Lata",
        "Lambamania",
        "Fazenda Chico Bento",
        "Maria Chiquinha"
    ]
  },
  {
    "id": "2",
    "img": "img/1992.jpg",
    "name": "Sábado à Noite",
    "description": "1992 • Álbum",
    "link": "https://www.letras.mus.br/sandy-e-junior-musicas/discografia/sabado-a-noite-1992/",
    "list": [
        "Sábado à Noite",
        "A Resposta da Mariquinha",
        "O Vira",
        "Guardiã dos Animais",
        "O Sítio da Vovó",
        "O Sabe Tudo",
        "Vamos Construir",
        "Como Nós Somos Unidos",
        "Infância Careta",
        "Pó Pra Tapar Taio",
        "Medo de Crescer",
        "Criança, Vida e Luz"
    ]
  },
  {
    "id": "3",
    "img": "img/1993.jpg",
    "name": "Tô Ligado em Você",
    "description": "1993 • Álbum",
    "link": "https://www.letras.mus.br/sandy-e-junior-musicas/discografia/to-ligado-em-voce-1993/",
    "list": [
        "Splish Splash",
        "Primeiro Amor",
        "Tô Ligado em Você",
        "Eu Quero Voar",
        "Capitão Sujeira",
        "Como é Bom Gostar",
        "Ciumeira",
        "Não Somos Números",
        "Coça Coça",
        "Casa Assombrada",
        "Coitadinho do Jacaré"
    ]
  },
  {
    "id": "4",
    "img": "img/1994.jpg",
    "name": "Pra Dançar com Você",
    "description": "1994 • Álbum",
    "link": "https://www.letras.mus.br/sandy-e-junior-musicas/discografia/pra-dancar-com-voce-1994/",
    "list": [
        "Com Você",
        "Ser Criança",
        "O Pica-Pau",
        "Pra Dançar Com Você",
        "Eu Quero é Mais",
        "Nascemos Pra Cantar",
        "Dance, Dance, Dance",
        "Mais Que Uma Sombra / Troque a Pilha / Esteja no Ar",
        "Filme Triste",
        "Maria Mole",
        "Pinguilim",
        "Criança Esperança",
        "X da Questão"
    ]
  },
  {
    "id": "5",
    "img": "img/1995.jpg",
    "name": "Você É D+",
    "description": "1995 • Álbum",
    "link": "https://www.letras.mus.br/sandy-e-junior-musicas/discografia/voce-e-d-1995/",
    "list": [
        "Rap do Aniversário",
        "Além da imaginação",
        "Sonho Real",
        "Roller Boys",
        "A Gente Se Gosta Demais",
        "Marilyn",
        "Vamos Ver a Galera Agitar",
        "O Universo Precisa de Vocês (Power Rangers)",
        "Voce É Demais",
        "Vai Ter Que Rebolar",
        "É Cedo Pra Amar Assim",
        "Vamos nessa que tá bom à  bessa",
        "Doce como o mel",
        "Tintim ( Um Brinde Ao Amor)"
    ]
  },
  {
    "id": "6",
    "img": "img/1995_2.jpg",
    "name": "Sonho Azul",
    "description": "1995 • Álbum",
    "link": "https://www.letras.mus.br/sandy-e-junior-musicas/discografia/sonho-azul-1995/",
    "list": [
        "Beijo É Bom",
        "Como Eu Te Amo",
        "Little Cowboy",
        "Sonho Azul",
        "Felicidade Como For",
        "Inesquecível",
        "Pega Na Mentira",
        "Pot-Pourri Bee Gees",
        "Mais Um Tempo Pra Crescer",
        "Não Abuse de Mim",
        "Ilusão",
        "Eu Acho que Pirei",
        "Ce Tá Queimando o Meu Filme",
        "Pomponeta",
        "Era Uma Vez"
    ]
  },
  {
    "id": "8",
    "img": "img/1996.jpg",
    "name": "Dig-Dig-Joy",
    "description": "1996 • Álbum",
    "link": "https://www.letras.mus.br/sandy-e-junior-musicas/discografia/dig-dig-joy-1996/",
    "list": [
        "Etc... e Tal",
        "Como Um Flash",
        "Eu Vou Te Namorar",
        "Golpe Certo",
        "Dias e Noites",
        "Férias de Julho",
        "Quero Saber",
        "Dig-Dig-Joy",
        "Não Ter",
        "Jambalaya",
        "Me Apaixonei",
        "Mala Sem Alça",
        "Mamãe Não Me Falou",
        "Cada Coisa Em Seu Lugar"
    ]
  },
  {
    "id": "9",
    "img": "img/1997.jpg",
    "name": "Nascemos pra cantar",
    "description": "1997 • Álbum",
    "link": "https://www.letras.mus.br/sandy-e-junior-musicas/discografia/nascemos-pra-cantar-1997/",
    "list": [
        "Inesquecível",
        "Primeiro Amor",
        "Sábado a Noite",
        "Abra a Porta, Mariquinha - Resposta da Mariquinha",
        "Não Ter",
        "Etc... e Tal",
        "Com Você",
        "Dig-Dig-Joy",
        "Splish Splash",
        "Era Uma Vez",
        "Tô ligado em você",
        "Como Eu Te Amo",
        "Nascemos Pra Cantar",
        "Vamos Construir"
    ]
  },
  {
    "id": "10",
    "img": "img/1997_2.jpg",
    "name": "Criança ajuda Criança",
    "description": "1997 • Álbum",
    "link": "https://www.letras.mus.br/sandy-e-junior-musicas/discografia/crianca-ajuda-crianca-1997/",
    "list": [
        "Maria Chiquinha",
        "Abra a Porta, Mariquinha - Resposta da Mariquinha",
        "Splish Splash",
        "Criança Esperança",
        "O Pica-Pau",
        "Dance, Dance, Dance",
        "Primeiro Amor",
        "Dig-Dig-Joy",
        "Não Ter",
        "Etc... e Tal"
    ]
  },
  {
    "id": "11",
    "img": "img/1997_3.jpg",
    "name": "Minha História",
    "description": "1997 • Álbum",
    "link": "https://www.letras.mus.br/sandy-e-junior-musicas/discografia/minha-historia-1997/",
    "list": [
        "Não Ter",
        "Casamento Natural",
        "Vamos Construir",
        "Splish Splash",
        "Primeiro Amor",
        "Tô Ligado Em Você (You're The One That I Want)",
        "Com Você",
        "Maria Chiquinha",
        "Abra a Porta, Mariquinha - Resposta da Mariquinha",
        "Sábado a Noite",
        "Etc... e Tal",
        "Nascemos Pra Cantar",
        "Dig-Dig-Joy",
        "Criança Esperança"
    ]
  },
  {
    "id": "12",
    "img": "img/1997_4.jpg",
    "name": "Dig-Dig-Joy Tour",
    "description": "1997 • Álbum",
    "link": "https://www.letras.mus.br/sandy-e-junior-musicas/discografia/dig-dig-joy-tour-1997/",
    "list": [
        "Como Um Flash",
        "Com Você",
        "Golpe Certo",
        "Vai Ter Que Rebolar",
        "Etc... e Tal",
        "Maria Chiquinha",
        "Sábado a Noite",
        "Abra a Porta, Mariquinha - Resposta da Mariquinha",
        "Jambalaya",
        "O Pica-Pau",
        "Dig-Dig-Joy",
        "Inesquecível",
        "Beijo é Bom",
        "Pinguilim",
        "Não Ter",
        "O Universo Precisa de Vocês (Power Rangers)",
        "Quero Saber",
        "Vamos Ver a Galera Agitar",
        "Pout-Pourri Bee Gees"
    ]
  },
  {
    "id": "13",
    "img": "img/1998.jpg",
    "name": "Era uma vez",
    "description": "1998 • Álbum",
    "link": "https://www.letras.mus.br/sandy-e-junior-musicas/discografia/era-uma-vez-1998/",
    "list": [
        "Como Um Flash",
        "Com Você",
        "Beijo é Bom",
        "Inesquecível",
        "Dig-Dig-Joy",
        "Vai Ter Que Rebolar",
        "Etc... e Tal",
        "My Heart Will Go On",
        "Era Uma Vez",
        "Não Ter",
        "Eu Acho que Pirei",
        "Em Cada Sonho",
        "Cadê Você Que Não Está",
        "No Fundo Do Coração"
    ]
  },
  {
    "id": "14",
    "img": "img/1998_2.jpg",
    "name": "Millennium",
    "description": "1998 • Álbum",
    "link": "https://www.letras.mus.br/sandy-e-junior-musicas/discografia/millennium-1998/",
    "list": [
        "Era Uma Vez",
        "Inesquecível",
        "Etc... e Tal",
        "Não Ter",
        "Sábado a Noite",
        "Little Cowboy (I Want To Be A Cowboy's Sweetheart)",
        "Sonho Azul",
        "Abra a Porta, Mariquinha - Resposta da Mariquinha",
        "Dig-Dig-Joy",
        "Eu Vou Te Namorar",
        "Aniversário Do Tatu",
        "Vai Ter Que Rebolar",
        "Com Você",
        "Jambalaya",
        "Casamento Natural",
        "Pout-Pourri Bee Gees",
        "Nascemos Pra Cantar",
        "Criança Esperança",
        "Maria Chiquinha",
        "Vamos Construir"
    ]
  },
  {
    "id": "7",
    "img": "img/2001.jpg",
    "name": "Sandy e Junior",
    "description": "2001 • Álbum",
    "link": "https://www.letras.mus.br/sandy-e-junior-musicas/discografia/sandy-e-junior-2001/",
    "list": [
        "Não Dá Pra Não Pensar",
        "O Amor Faz",
        "Cai a Chuva / Me Diz",
        "Baby, Liga Pra Mim",
        "Quando Você Passa (Turu Turu)",
        "Chuva de Prata",
        "Adeus",
        "A Gente Dá Certo",
        "Nada é Por Acaso",
        "A Estrela que Mais Brilhar",
        "Deixa Eu tentar",
        "Endless Love",
        "Me Leve Com Você",
        "O Lugar Perfeito Pro Amor Viver"
    ]
  }
]
