-- MySQL Script generated by MySQL Workbench
-- Tue Oct 26 19:54:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cdg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cdg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cdg` DEFAULT CHARACTER SET utf8 ;
USE `cdg` ;

-- -----------------------------------------------------
-- Table `cdg`.`artista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdg`.`artista` ;

CREATE TABLE IF NOT EXISTS `cdg`.`artista` (
  `idArtista` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `generoMusical` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idArtista`),
  UNIQUE INDEX `idArtista_UNIQUE` (`idArtista` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cdg`.`palco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdg`.`palco` ;

CREATE TABLE IF NOT EXISTS `cdg`.`palco` (
  `idPalco` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPalco`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cdg`.`artistaPalco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdg`.`artistaPalco` ;

CREATE TABLE IF NOT EXISTS `cdg`.`artistaPalco` (
  `idArtistaPalco` INT NOT NULL AUTO_INCREMENT,
  `Artista_idArtista` INT NOT NULL,
  `Palco_idPalco` INT NOT NULL,
  `horarioArtista` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idArtistaPalco`),
  INDEX `fk_Artista_has_Palco_Palco1_idx` (`Palco_idPalco` ASC) VISIBLE,
  INDEX `fk_Artista_has_Palco_Artista1_idx` (`Artista_idArtista` ASC) VISIBLE,
  CONSTRAINT `fk_Artista_has_Palco_Artista1`
    FOREIGN KEY (`Artista_idArtista`)
    REFERENCES `cdg`.`artista` (`idArtista`),
  CONSTRAINT `fk_Artista_has_Palco_Palco1`
    FOREIGN KEY (`Palco_idPalco`)
    REFERENCES `cdg`.`palco` (`idPalco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cdg`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdg`.`evento` ;

CREATE TABLE IF NOT EXISTS `cdg`.`evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `palco_idPalco` INT NOT NULL,
  PRIMARY KEY (`idEvento`, `palco_idPalco`),
  UNIQUE INDEX `idEvento_UNIQUE` (`idEvento` ASC) VISIBLE,
  INDEX `fk_evento_palco1_idx` (`palco_idPalco` ASC) VISIBLE,
  CONSTRAINT `fk_evento_palco1`
    FOREIGN KEY (`palco_idPalco`)
    REFERENCES `cdg`.`palco` (`idPalco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = '			';


-- -----------------------------------------------------
-- Table `cdg`.`participante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdg`.`participante` ;

CREATE TABLE IF NOT EXISTS `cdg`.`participante` (
  `idParticipante` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `dataNasc` DATE NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idParticipante`),
  UNIQUE INDEX `idParticipante_UNIQUE` (`idParticipante` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cdg`.`ingresso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdg`.`ingresso` ;

CREATE TABLE IF NOT EXISTS `cdg`.`ingresso` (
  `idIngresso` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  `Evento_idEvento` INT NOT NULL,
  `Participante_idParticipante` INT NOT NULL,
  PRIMARY KEY (`idIngresso`, `Evento_idEvento`, `Participante_idParticipante`),
  UNIQUE INDEX `idIngresso_UNIQUE` (`idIngresso` ASC) VISIBLE,
  INDEX `fk_Ingresso_Evento1_idx` (`Evento_idEvento` ASC) VISIBLE,
  INDEX `fk_Ingresso_Participante1_idx` (`Participante_idParticipante` ASC) VISIBLE,
  CONSTRAINT `fk_Ingresso_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `cdg`.`evento` (`idEvento`),
  CONSTRAINT `fk_Ingresso_Participante1`
    FOREIGN KEY (`Participante_idParticipante`)
    REFERENCES `cdg`.`participante` (`idParticipante`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cdg`.`musica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cdg`.`musica` ;

CREATE TABLE IF NOT EXISTS `cdg`.`musica` (
  `idMusica` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Artista_idArtista` INT NOT NULL,
  PRIMARY KEY (`idMusica`, `Artista_idArtista`),
  UNIQUE INDEX `idMúsica_UNIQUE` (`idMusica` ASC) VISIBLE,
  INDEX `fk_Música_Artista1_idx` (`Artista_idArtista` ASC) VISIBLE,
  CONSTRAINT `fk_Música_Artista1`
    FOREIGN KEY (`Artista_idArtista`)
    REFERENCES `cdg`.`artista` (`idArtista`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
